// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/state_context_pb2/state_context.proto

/*
Package state_context_pb2 is a generated protocol buffer package.

It is generated from these files:
	sawtooth_sdk/protobuf/state_context_pb2/state_context.proto

It has these top-level messages:
	Entry
	TpStateGetRequest
	TpStateGetResponse
	TpStateSetRequest
	TpStateSetResponse
	TpStateDeleteRequest
	TpStateDeleteResponse
	TpAddReceiptDataRequest
	TpAddReceiptDataResponse
	TpAddEventRequest
	TpAddEventResponse
*/
package state_context_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import events "sawtooth_sdk/protobuf/events_pb2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TpStateGetResponse_Status int32

const (
	TpStateGetResponse_OK                  TpStateGetResponse_Status = 0
	TpStateGetResponse_AUTHORIZATION_ERROR TpStateGetResponse_Status = 1
)

var TpStateGetResponse_Status_name = map[int32]string{
	0: "OK",
	1: "AUTHORIZATION_ERROR",
}
var TpStateGetResponse_Status_value = map[string]int32{
	"OK": 0,
	"AUTHORIZATION_ERROR": 1,
}

func (x TpStateGetResponse_Status) String() string {
	return proto.EnumName(TpStateGetResponse_Status_name, int32(x))
}
func (TpStateGetResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type TpStateSetResponse_Status int32

const (
	TpStateSetResponse_OK                  TpStateSetResponse_Status = 0
	TpStateSetResponse_AUTHORIZATION_ERROR TpStateSetResponse_Status = 1
)

var TpStateSetResponse_Status_name = map[int32]string{
	0: "OK",
	1: "AUTHORIZATION_ERROR",
}
var TpStateSetResponse_Status_value = map[string]int32{
	"OK": 0,
	"AUTHORIZATION_ERROR": 1,
}

func (x TpStateSetResponse_Status) String() string {
	return proto.EnumName(TpStateSetResponse_Status_name, int32(x))
}
func (TpStateSetResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type TpStateDeleteResponse_Status int32

const (
	TpStateDeleteResponse_OK                  TpStateDeleteResponse_Status = 0
	TpStateDeleteResponse_AUTHORIZATION_ERROR TpStateDeleteResponse_Status = 1
)

var TpStateDeleteResponse_Status_name = map[int32]string{
	0: "OK",
	1: "AUTHORIZATION_ERROR",
}
var TpStateDeleteResponse_Status_value = map[string]int32{
	"OK": 0,
	"AUTHORIZATION_ERROR": 1,
}

func (x TpStateDeleteResponse_Status) String() string {
	return proto.EnumName(TpStateDeleteResponse_Status_name, int32(x))
}
func (TpStateDeleteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type TpAddReceiptDataResponse_Status int32

const (
	TpAddReceiptDataResponse_OK    TpAddReceiptDataResponse_Status = 0
	TpAddReceiptDataResponse_ERROR TpAddReceiptDataResponse_Status = 1
)

var TpAddReceiptDataResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TpAddReceiptDataResponse_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TpAddReceiptDataResponse_Status) String() string {
	return proto.EnumName(TpAddReceiptDataResponse_Status_name, int32(x))
}
func (TpAddReceiptDataResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

type TpAddEventResponse_Status int32

const (
	TpAddEventResponse_OK    TpAddEventResponse_Status = 0
	TpAddEventResponse_ERROR TpAddEventResponse_Status = 1
)

var TpAddEventResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TpAddEventResponse_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TpAddEventResponse_Status) String() string {
	return proto.EnumName(TpAddEventResponse_Status_name, int32(x))
}
func (TpAddEventResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

// An entry in the State
type Entry struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// A request from a handler/tp for the values at a series of addresses
type TpStateGetRequest struct {
	// The context id that references a context in the contextmanager
	ContextId string   `protobuf:"bytes,1,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *TpStateGetRequest) Reset()                    { *m = TpStateGetRequest{} }
func (m *TpStateGetRequest) String() string            { return proto.CompactTextString(m) }
func (*TpStateGetRequest) ProtoMessage()               {}
func (*TpStateGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TpStateGetRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

func (m *TpStateGetRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// A response from the contextmanager/validator with a series of State entries
type TpStateGetResponse struct {
	Entries []*Entry                  `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Status  TpStateGetResponse_Status `protobuf:"varint,2,opt,name=status,enum=TpStateGetResponse_Status" json:"status,omitempty"`
}

func (m *TpStateGetResponse) Reset()                    { *m = TpStateGetResponse{} }
func (m *TpStateGetResponse) String() string            { return proto.CompactTextString(m) }
func (*TpStateGetResponse) ProtoMessage()               {}
func (*TpStateGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TpStateGetResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *TpStateGetResponse) GetStatus() TpStateGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpStateGetResponse_OK
}

// A request from the handler/tp to put entries in the state of a context
type TpStateSetRequest struct {
	ContextId string   `protobuf:"bytes,1,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	Entries   []*Entry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *TpStateSetRequest) Reset()                    { *m = TpStateSetRequest{} }
func (m *TpStateSetRequest) String() string            { return proto.CompactTextString(m) }
func (*TpStateSetRequest) ProtoMessage()               {}
func (*TpStateSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TpStateSetRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

func (m *TpStateSetRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// A response from the contextmanager/validator with the addresses that were set
type TpStateSetResponse struct {
	Addresses []string                  `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	Status    TpStateSetResponse_Status `protobuf:"varint,2,opt,name=status,enum=TpStateSetResponse_Status" json:"status,omitempty"`
}

func (m *TpStateSetResponse) Reset()                    { *m = TpStateSetResponse{} }
func (m *TpStateSetResponse) String() string            { return proto.CompactTextString(m) }
func (*TpStateSetResponse) ProtoMessage()               {}
func (*TpStateSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TpStateSetResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *TpStateSetResponse) GetStatus() TpStateSetResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpStateSetResponse_OK
}

// A request from the handler/tp to delete state entries at an collection of addresses
type TpStateDeleteRequest struct {
	ContextId string   `protobuf:"bytes,1,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *TpStateDeleteRequest) Reset()                    { *m = TpStateDeleteRequest{} }
func (m *TpStateDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*TpStateDeleteRequest) ProtoMessage()               {}
func (*TpStateDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TpStateDeleteRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

func (m *TpStateDeleteRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// A response form the contextmanager/validator with the addresses that were deleted
type TpStateDeleteResponse struct {
	Addresses []string                     `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	Status    TpStateDeleteResponse_Status `protobuf:"varint,2,opt,name=status,enum=TpStateDeleteResponse_Status" json:"status,omitempty"`
}

func (m *TpStateDeleteResponse) Reset()                    { *m = TpStateDeleteResponse{} }
func (m *TpStateDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*TpStateDeleteResponse) ProtoMessage()               {}
func (*TpStateDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TpStateDeleteResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *TpStateDeleteResponse) GetStatus() TpStateDeleteResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpStateDeleteResponse_OK
}

// The request from the transaction processor to the validator append data
// to a transaction receipt
type TpAddReceiptDataRequest struct {
	// The context id that references a context in the contextmanager
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	DataType  string `protobuf:"bytes,2,opt,name=data_type,json=dataType" json:"data_type,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TpAddReceiptDataRequest) Reset()                    { *m = TpAddReceiptDataRequest{} }
func (m *TpAddReceiptDataRequest) String() string            { return proto.CompactTextString(m) }
func (*TpAddReceiptDataRequest) ProtoMessage()               {}
func (*TpAddReceiptDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TpAddReceiptDataRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

func (m *TpAddReceiptDataRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *TpAddReceiptDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// The response from the validator to the transaction processor to verify that
// data has been appended to a transaction receipt
type TpAddReceiptDataResponse struct {
	Status TpAddReceiptDataResponse_Status `protobuf:"varint,2,opt,name=status,enum=TpAddReceiptDataResponse_Status" json:"status,omitempty"`
}

func (m *TpAddReceiptDataResponse) Reset()                    { *m = TpAddReceiptDataResponse{} }
func (m *TpAddReceiptDataResponse) String() string            { return proto.CompactTextString(m) }
func (*TpAddReceiptDataResponse) ProtoMessage()               {}
func (*TpAddReceiptDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TpAddReceiptDataResponse) GetStatus() TpAddReceiptDataResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpAddReceiptDataResponse_OK
}

type TpAddEventRequest struct {
	ContextId string        `protobuf:"bytes,1,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	Event     *events.Event `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
}

func (m *TpAddEventRequest) Reset()                    { *m = TpAddEventRequest{} }
func (m *TpAddEventRequest) String() string            { return proto.CompactTextString(m) }
func (*TpAddEventRequest) ProtoMessage()               {}
func (*TpAddEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TpAddEventRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

func (m *TpAddEventRequest) GetEvent() *events.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type TpAddEventResponse struct {
	Status TpAddEventResponse_Status `protobuf:"varint,2,opt,name=status,enum=TpAddEventResponse_Status" json:"status,omitempty"`
}

func (m *TpAddEventResponse) Reset()                    { *m = TpAddEventResponse{} }
func (m *TpAddEventResponse) String() string            { return proto.CompactTextString(m) }
func (*TpAddEventResponse) ProtoMessage()               {}
func (*TpAddEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TpAddEventResponse) GetStatus() TpAddEventResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpAddEventResponse_OK
}

func init() {
	proto.RegisterType((*Entry)(nil), "Entry")
	proto.RegisterType((*TpStateGetRequest)(nil), "TpStateGetRequest")
	proto.RegisterType((*TpStateGetResponse)(nil), "TpStateGetResponse")
	proto.RegisterType((*TpStateSetRequest)(nil), "TpStateSetRequest")
	proto.RegisterType((*TpStateSetResponse)(nil), "TpStateSetResponse")
	proto.RegisterType((*TpStateDeleteRequest)(nil), "TpStateDeleteRequest")
	proto.RegisterType((*TpStateDeleteResponse)(nil), "TpStateDeleteResponse")
	proto.RegisterType((*TpAddReceiptDataRequest)(nil), "TpAddReceiptDataRequest")
	proto.RegisterType((*TpAddReceiptDataResponse)(nil), "TpAddReceiptDataResponse")
	proto.RegisterType((*TpAddEventRequest)(nil), "TpAddEventRequest")
	proto.RegisterType((*TpAddEventResponse)(nil), "TpAddEventResponse")
	proto.RegisterEnum("TpStateGetResponse_Status", TpStateGetResponse_Status_name, TpStateGetResponse_Status_value)
	proto.RegisterEnum("TpStateSetResponse_Status", TpStateSetResponse_Status_name, TpStateSetResponse_Status_value)
	proto.RegisterEnum("TpStateDeleteResponse_Status", TpStateDeleteResponse_Status_name, TpStateDeleteResponse_Status_value)
	proto.RegisterEnum("TpAddReceiptDataResponse_Status", TpAddReceiptDataResponse_Status_name, TpAddReceiptDataResponse_Status_value)
	proto.RegisterEnum("TpAddEventResponse_Status", TpAddEventResponse_Status_name, TpAddEventResponse_Status_value)
}

func init() {
	proto.RegisterFile("sawtooth_sdk/protobuf/state_context_pb2/state_context.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0x36, 0x77, 0x36, 0x35, 0xa3, 0x48, 0xbb, 0x5a, 0x7a, 0xb4, 0x16, 0x8e, 0x3c, 0x55, 0xd0,
	0x2d, 0x9c, 0x14, 0x04, 0x9f, 0x4e, 0x7a, 0xe8, 0x21, 0x78, 0x65, 0x13, 0x5f, 0xfa, 0x12, 0x72,
	0xdd, 0x11, 0x83, 0x92, 0xa4, 0xd9, 0x3d, 0xb5, 0x3f, 0xc3, 0x07, 0xf1, 0xef, 0xba, 0xbb, 0xd9,
	0x5c, 0xd3, 0x24, 0x85, 0x88, 0xf7, 0xb6, 0xfb, 0xed, 0xec, 0xb7, 0xdf, 0x37, 0x3b, 0x33, 0xf0,
	0x46, 0xc4, 0x3f, 0x64, 0x96, 0xc9, 0x2f, 0x91, 0xe0, 0x5f, 0x4f, 0xf2, 0x22, 0x93, 0xd9, 0x72,
	0xf5, 0xf9, 0x44, 0xc8, 0x58, 0x62, 0x74, 0x99, 0xa5, 0x12, 0x7f, 0xca, 0x28, 0x5f, 0x4e, 0x6e,
	0x23, 0xd4, 0x04, 0x1e, 0xbc, 0xec, 0xbe, 0x8c, 0xdf, 0x31, 0x95, 0xc2, 0xdc, 0x2a, 0x97, 0x65,
	0xb8, 0x7f, 0x0a, 0x5b, 0xb3, 0x54, 0x16, 0xd7, 0x64, 0x04, 0xdb, 0x31, 0xe7, 0x05, 0x0a, 0x31,
	0x72, 0xc6, 0xce, 0xb1, 0xc7, 0xaa, 0x2d, 0x21, 0x70, 0x9f, 0xc7, 0x32, 0x1e, 0x0d, 0x14, 0xfc,
	0x88, 0x99, 0xb5, 0x7f, 0x0e, 0xbb, 0x61, 0x1e, 0xe8, 0xe7, 0xdf, 0xa1, 0x64, 0x78, 0xb5, 0x42,
	0x21, 0xc9, 0x11, 0x40, 0xa5, 0x2e, 0xe1, 0x96, 0xc5, 0xb3, 0xc8, 0x9c, 0x93, 0x67, 0xe0, 0x59,
	0x4a, 0x14, 0x8a, 0x6c, 0xa8, 0x4f, 0xd7, 0x80, 0xff, 0xdb, 0x01, 0x52, 0xa7, 0x14, 0x79, 0x96,
	0x0a, 0x24, 0x63, 0xd8, 0x56, 0x6a, 0x8b, 0x04, 0xb5, 0xac, 0xe1, 0xf1, 0xc3, 0x89, 0x4b, 0x8d,
	0x5e, 0x56, 0xc1, 0x64, 0x02, 0xae, 0xce, 0xc3, 0x4a, 0x18, 0x81, 0x8f, 0x27, 0x07, 0xb4, 0x4d,
	0x43, 0x03, 0x13, 0xc1, 0x6c, 0xa4, 0xff, 0x1c, 0xdc, 0x12, 0x21, 0x2e, 0x0c, 0x16, 0x1f, 0x76,
	0xee, 0x91, 0x7d, 0x78, 0x32, 0xfd, 0x14, 0xbe, 0x5f, 0xb0, 0xf9, 0xc5, 0x34, 0x9c, 0x2f, 0x3e,
	0x46, 0x33, 0xc6, 0x16, 0x6c, 0xc7, 0xf1, 0xc3, 0xb5, 0xd3, 0xa0, 0xb7, 0xd3, 0x9a, 0xe8, 0x41,
	0xa7, 0x68, 0xff, 0xd7, 0x8d, 0xdb, 0xa0, 0xe6, 0xf6, 0x56, 0x8a, 0x9c, 0x46, 0x8a, 0xee, 0x76,
	0x1a, 0x6c, 0xc4, 0x69, 0x00, 0x4f, 0x2d, 0xdf, 0x19, 0x7e, 0x43, 0x89, 0x1b, 0xf9, 0xd6, 0x3f,
	0x0e, 0xec, 0x35, 0x58, 0x7b, 0x79, 0x3d, 0x6d, 0x78, 0x3d, 0xa2, 0x9d, 0x2c, 0xff, 0x61, 0x37,
	0x81, 0xfd, 0x30, 0x9f, 0x72, 0xce, 0xf0, 0x12, 0x93, 0x5c, 0x9e, 0xa9, 0xb2, 0xee, 0xe9, 0xf8,
	0x10, 0x3c, 0xdd, 0x04, 0x91, 0xbc, 0xce, 0xd1, 0xc8, 0xf3, 0xd8, 0x03, 0x0d, 0x84, 0x6a, 0xbf,
	0xee, 0x96, 0x61, 0xad, 0x5b, 0xae, 0x60, 0xd4, 0x7e, 0xca, 0xa6, 0xe1, 0x75, 0xc3, 0xe8, 0x98,
	0xde, 0x15, 0xda, 0xf4, 0x7a, 0xd8, 0xf2, 0xea, 0xa9, 0x66, 0xb6, 0xee, 0x4c, 0x83, 0x2a, 0x9e,
	0x99, 0x6e, 0xf6, 0xde, 0x3f, 0xb9, 0x65, 0x66, 0x83, 0x51, 0x62, 0x8a, 0xd6, 0x5c, 0x2e, 0x41,
	0x1f, 0x75, 0xc5, 0xde, 0x30, 0x5a, 0xf9, 0x5d, 0x35, 0xd9, 0x0c, 0xfa, 0x17, 0xe1, 0x6f, 0x5f,
	0xc0, 0x5e, 0x35, 0xc1, 0xa8, 0x9a, 0x60, 0xb4, 0x9a, 0x60, 0xe7, 0xce, 0xc5, 0x6e, 0x6b, 0x02,
	0x2e, 0x5d, 0x73, 0xfc, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x2a, 0xb1, 0xfa, 0x33,
	0x05, 0x00, 0x00,
}
