// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/processor_pb2/processor.proto

/*
Package processor_pb2 is a generated protocol buffer package.

It is generated from these files:
	sawtooth_sdk/protobuf/processor_pb2/processor.proto

It has these top-level messages:
	TpRegisterRequest
	TpRegisterResponse
	TpUnregisterRequest
	TpUnregisterResponse
	TpProcessRequest
	TpProcessResponse
	TpPing
	TpPingResponse
*/
package processor_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TpRegisterResponse_Status int32

const (
	TpRegisterResponse_OK    TpRegisterResponse_Status = 0
	TpRegisterResponse_ERROR TpRegisterResponse_Status = 1
)

var TpRegisterResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TpRegisterResponse_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TpRegisterResponse_Status) String() string {
	return proto.EnumName(TpRegisterResponse_Status_name, int32(x))
}
func (TpRegisterResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type TpUnregisterResponse_Status int32

const (
	TpUnregisterResponse_OK    TpUnregisterResponse_Status = 0
	TpUnregisterResponse_ERROR TpUnregisterResponse_Status = 1
)

var TpUnregisterResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TpUnregisterResponse_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TpUnregisterResponse_Status) String() string {
	return proto.EnumName(TpUnregisterResponse_Status_name, int32(x))
}
func (TpUnregisterResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type TpProcessResponse_Status int32

const (
	TpProcessResponse_OK                  TpProcessResponse_Status = 0
	TpProcessResponse_INVALID_TRANSACTION TpProcessResponse_Status = 1
	TpProcessResponse_INTERNAL_ERROR      TpProcessResponse_Status = 2
)

var TpProcessResponse_Status_name = map[int32]string{
	0: "OK",
	1: "INVALID_TRANSACTION",
	2: "INTERNAL_ERROR",
}
var TpProcessResponse_Status_value = map[string]int32{
	"OK": 0,
	"INVALID_TRANSACTION": 1,
	"INTERNAL_ERROR":      2,
}

func (x TpProcessResponse_Status) String() string {
	return proto.EnumName(TpProcessResponse_Status_name, int32(x))
}
func (TpProcessResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type TpPingResponse_Status int32

const (
	TpPingResponse_OK    TpPingResponse_Status = 0
	TpPingResponse_ERROR TpPingResponse_Status = 1
)

var TpPingResponse_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TpPingResponse_Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TpPingResponse_Status) String() string {
	return proto.EnumName(TpPingResponse_Status_name, int32(x))
}
func (TpPingResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

// The registration request from the transaction processor to the
// validator/executor
type TpRegisterRequest struct {
	// A settled upon name for the capabilities of the transaction processor.
	// For example: intkey, xo
	Family string `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	// The version supported.  For example:
	//      1.0  for version 1.0
	//      2.1  for version 2.1
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// The supported encodings.
	// 'application/cbor', 'application/protobuf', etc
	Encoding string `protobuf:"bytes,3,opt,name=encoding" json:"encoding,omitempty"`
	// The namespaces this transaction processor expects to interact with
	// when processing transations matching this specification; will be
	// enforced by the state API on the validator.
	Namespaces []string `protobuf:"bytes,4,rep,name=namespaces" json:"namespaces,omitempty"`
}

func (m *TpRegisterRequest) Reset()                    { *m = TpRegisterRequest{} }
func (m *TpRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*TpRegisterRequest) ProtoMessage()               {}
func (*TpRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TpRegisterRequest) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *TpRegisterRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TpRegisterRequest) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *TpRegisterRequest) GetNamespaces() []string {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

// A response sent from the validator to the transaction processor
// acknowledging the registration
type TpRegisterResponse struct {
	Status TpRegisterResponse_Status `protobuf:"varint,1,opt,name=status,enum=TpRegisterResponse_Status" json:"status,omitempty"`
}

func (m *TpRegisterResponse) Reset()                    { *m = TpRegisterResponse{} }
func (m *TpRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*TpRegisterResponse) ProtoMessage()               {}
func (*TpRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TpRegisterResponse) GetStatus() TpRegisterResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpRegisterResponse_OK
}

// The unregistration request from the transaction processor to the
// validator/executor. The correct handlers are determined from the
// zeromq identity of the tp, on the validator side.
type TpUnregisterRequest struct {
}

func (m *TpUnregisterRequest) Reset()                    { *m = TpUnregisterRequest{} }
func (m *TpUnregisterRequest) String() string            { return proto.CompactTextString(m) }
func (*TpUnregisterRequest) ProtoMessage()               {}
func (*TpUnregisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// A response sent from the validator to the transaction processor
// acknowledging the unregistration
type TpUnregisterResponse struct {
	Status TpUnregisterResponse_Status `protobuf:"varint,1,opt,name=status,enum=TpUnregisterResponse_Status" json:"status,omitempty"`
}

func (m *TpUnregisterResponse) Reset()                    { *m = TpUnregisterResponse{} }
func (m *TpUnregisterResponse) String() string            { return proto.CompactTextString(m) }
func (*TpUnregisterResponse) ProtoMessage()               {}
func (*TpUnregisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TpUnregisterResponse) GetStatus() TpUnregisterResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpUnregisterResponse_OK
}

// The request from the validator/executor of the transaction processor
// to verify a transaction.
type TpProcessRequest struct {
	Header    []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	ContextId string `protobuf:"bytes,4,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
}

func (m *TpProcessRequest) Reset()                    { *m = TpProcessRequest{} }
func (m *TpProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*TpProcessRequest) ProtoMessage()               {}
func (*TpProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TpProcessRequest) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TpProcessRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TpProcessRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *TpProcessRequest) GetContextId() string {
	if m != nil {
		return m.ContextId
	}
	return ""
}

// The response from the transaction processor to the validator/executor
// used to respond about the validity of a transaction
type TpProcessResponse struct {
	Status TpProcessResponse_Status `protobuf:"varint,1,opt,name=status,enum=TpProcessResponse_Status" json:"status,omitempty"`
	// A message to include on responses in the cases where
	// status is either INVALID_TRANSACTION or INTERNAL_ERROR
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// Information that may be included with the response.
	// This information is an opaque, application-specific encoded block of
	// data that will be propagated back to the transaction submitter.
	ExtendedData []byte `protobuf:"bytes,3,opt,name=extended_data,json=extendedData,proto3" json:"extended_data,omitempty"`
}

func (m *TpProcessResponse) Reset()                    { *m = TpProcessResponse{} }
func (m *TpProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*TpProcessResponse) ProtoMessage()               {}
func (*TpProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TpProcessResponse) GetStatus() TpProcessResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpProcessResponse_OK
}

func (m *TpProcessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TpProcessResponse) GetExtendedData() []byte {
	if m != nil {
		return m.ExtendedData
	}
	return nil
}

type TpPing struct {
}

func (m *TpPing) Reset()                    { *m = TpPing{} }
func (m *TpPing) String() string            { return proto.CompactTextString(m) }
func (*TpPing) ProtoMessage()               {}
func (*TpPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type TpPingResponse struct {
	Status TpPingResponse_Status `protobuf:"varint,1,opt,name=status,enum=TpPingResponse_Status" json:"status,omitempty"`
}

func (m *TpPingResponse) Reset()                    { *m = TpPingResponse{} }
func (m *TpPingResponse) String() string            { return proto.CompactTextString(m) }
func (*TpPingResponse) ProtoMessage()               {}
func (*TpPingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TpPingResponse) GetStatus() TpPingResponse_Status {
	if m != nil {
		return m.Status
	}
	return TpPingResponse_OK
}

func init() {
	proto.RegisterType((*TpRegisterRequest)(nil), "TpRegisterRequest")
	proto.RegisterType((*TpRegisterResponse)(nil), "TpRegisterResponse")
	proto.RegisterType((*TpUnregisterRequest)(nil), "TpUnregisterRequest")
	proto.RegisterType((*TpUnregisterResponse)(nil), "TpUnregisterResponse")
	proto.RegisterType((*TpProcessRequest)(nil), "TpProcessRequest")
	proto.RegisterType((*TpProcessResponse)(nil), "TpProcessResponse")
	proto.RegisterType((*TpPing)(nil), "TpPing")
	proto.RegisterType((*TpPingResponse)(nil), "TpPingResponse")
	proto.RegisterEnum("TpRegisterResponse_Status", TpRegisterResponse_Status_name, TpRegisterResponse_Status_value)
	proto.RegisterEnum("TpUnregisterResponse_Status", TpUnregisterResponse_Status_name, TpUnregisterResponse_Status_value)
	proto.RegisterEnum("TpProcessResponse_Status", TpProcessResponse_Status_name, TpProcessResponse_Status_value)
	proto.RegisterEnum("TpPingResponse_Status", TpPingResponse_Status_name, TpPingResponse_Status_value)
}

func init() {
	proto.RegisterFile("sawtooth_sdk/protobuf/processor_pb2/processor.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x65, 0x53, 0x58, 0x9a, 0x51, 0x1a, 0x05, 0x97, 0x96, 0xa5, 0x14, 0x54, 0x99, 0x4b, 0x4f,
	0x46, 0xa4, 0x5c, 0x39, 0x04, 0xda, 0xc3, 0x8a, 0x6a, 0x53, 0xb9, 0x0b, 0x07, 0x24, 0xb4, 0x72,
	0xe2, 0x69, 0xba, 0xa2, 0xb5, 0x97, 0xb5, 0x03, 0xf4, 0xc8, 0xbf, 0xf1, 0x61, 0x38, 0xce, 0x6e,
	0x9a, 0x6c, 0xb8, 0xe4, 0xe6, 0xf7, 0xe6, 0x49, 0xf3, 0xe6, 0x8d, 0x07, 0x4e, 0x8c, 0xf8, 0x65,
	0xb5, 0xb6, 0xd7, 0x99, 0x91, 0xdf, 0xdf, 0x14, 0xa5, 0xb6, 0x7a, 0x34, 0xbd, 0x9a, 0x3d, 0xc6,
	0x68, 0x8c, 0x2e, 0xb3, 0x62, 0xd4, 0xbf, 0x47, 0xcc, 0x0b, 0xe8, 0x9f, 0x00, 0x9e, 0xa4, 0x05,
	0xc7, 0x49, 0x6e, 0x2c, 0x96, 0x1c, 0x7f, 0x4c, 0xd1, 0x58, 0xb2, 0x0f, 0xe1, 0x95, 0xb8, 0xcd,
	0x6f, 0xee, 0xa2, 0xe0, 0x28, 0x38, 0x6e, 0xf3, 0x0a, 0x91, 0x08, 0x1e, 0xff, 0xc4, 0xd2, 0xe4,
	0x5a, 0x45, 0x2d, 0x5f, 0xa8, 0x21, 0x39, 0x80, 0x6d, 0x54, 0x63, 0x2d, 0x73, 0x35, 0x89, 0xb6,
	0x7c, 0x69, 0x81, 0xc9, 0x2b, 0x00, 0x25, 0x6e, 0xd1, 0x14, 0xc2, 0xb5, 0x8e, 0x1e, 0x1e, 0x6d,
	0xb9, 0xea, 0x12, 0x43, 0x11, 0xc8, 0xb2, 0x05, 0x53, 0x68, 0x65, 0x90, 0xf4, 0x21, 0x34, 0x56,
	0xd8, 0xa9, 0xf1, 0x1e, 0xba, 0xfd, 0x03, 0xb6, 0x2e, 0x62, 0x97, 0x5e, 0xc1, 0x2b, 0x25, 0x7d,
	0x01, 0xe1, 0x9c, 0x21, 0x21, 0xb4, 0x86, 0x9f, 0x7a, 0x0f, 0x48, 0x1b, 0x1e, 0x9d, 0x71, 0x3e,
	0xe4, 0xbd, 0x80, 0xee, 0xc1, 0x6e, 0x5a, 0x7c, 0x56, 0xe5, 0xea, 0xac, 0x34, 0x87, 0xa7, 0xab,
	0x74, 0xd5, 0xff, 0x5d, 0xa3, 0xff, 0x21, 0xfb, 0x9f, 0x6c, 0x23, 0x07, 0x2e, 0xec, 0x5e, 0x5a,
	0x5c, 0xcc, 0x57, 0xb0, 0x94, 0xf5, 0x35, 0x0a, 0x89, 0xa5, 0xef, 0xd3, 0xe1, 0x15, 0x9a, 0x65,
	0x5d, 0x88, 0xbb, 0x1b, 0x2d, 0xa4, 0xcf, 0xba, 0xc3, 0x6b, 0x48, 0x0e, 0xa1, 0x6d, 0xf2, 0x89,
	0x72, 0x5d, 0x4a, 0xac, 0xc2, 0xbe, 0x27, 0xc8, 0x4b, 0x80, 0xb1, 0x56, 0x16, 0x7f, 0xdb, 0x2c,
	0x97, 0x2e, 0x6d, 0x5f, 0xae, 0x98, 0x58, 0xd2, 0xbf, 0x7e, 0xe1, 0x0b, 0x0f, 0xd5, 0xb0, 0x6f,
	0x1b, 0xc3, 0x3e, 0x67, 0x6b, 0x9a, 0xc6, 0xa4, 0x33, 0x7f, 0x6e, 0x83, 0x46, 0x4c, 0xb0, 0xfe,
	0x0b, 0x15, 0x24, 0xaf, 0x61, 0xc7, 0xf5, 0x42, 0x25, 0x51, 0x66, 0x52, 0x58, 0xe1, 0x3d, 0x76,
	0x78, 0xa7, 0x26, 0x4f, 0x1d, 0x47, 0xdf, 0xaf, 0x05, 0xf5, 0x0c, 0x76, 0xe3, 0xe4, 0xcb, 0xe0,
	0x3c, 0x3e, 0xcd, 0x52, 0x3e, 0x48, 0x2e, 0x07, 0x1f, 0xd3, 0x78, 0x98, 0xf4, 0x02, 0x42, 0xa0,
	0x1b, 0x27, 0xe9, 0x19, 0x4f, 0x06, 0xe7, 0xd9, 0x3c, 0xca, 0x16, 0xdd, 0x86, 0xd0, 0x39, 0x74,
	0xbf, 0x8b, 0x7e, 0x83, 0xee, 0xfc, 0xb5, 0x18, 0x86, 0x35, 0x86, 0xd9, 0x67, 0xab, 0x82, 0x4d,
	0x76, 0xf6, 0xe1, 0x18, 0xf6, 0xea, 0xbb, 0x62, 0xee, 0xae, 0x58, 0x7d, 0x57, 0x17, 0xc1, 0xd7,
	0x9d, 0x95, 0xd3, 0x1a, 0x85, 0xbe, 0x74, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xf2, 0x83,
	0x01, 0x88, 0x03, 0x00, 0x00,
}
