// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/block_pb2/block.proto

/*
Package block_pb2 is a generated protocol buffer package.

It is generated from these files:
	sawtooth_sdk/protobuf/block_pb2/block.proto

It has these top-level messages:
	BlockHeader
	Block
*/
package block_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import batch "sawtooth_sdk/protobuf/batch_pb2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	// Block number in the chain
	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
	// The header_signature of the previous block that was added to the chain.
	PreviousBlockId string `protobuf:"bytes,2,opt,name=previous_block_id,json=previousBlockId" json:"previous_block_id,omitempty"`
	// Public key for the component internal to the validator that
	// signed the BlockHeader
	SignerPubkey string `protobuf:"bytes,3,opt,name=signer_pubkey,json=signerPubkey" json:"signer_pubkey,omitempty"`
	// List of batch.header_signatures that match the order of batches
	// required for the block
	BatchIds []string `protobuf:"bytes,4,rep,name=batch_ids,json=batchIds" json:"batch_ids,omitempty"`
	// Bytes that are set and verified by the consensus algorithm used to
	// create and validate the block
	Consensus []byte `protobuf:"bytes,5,opt,name=consensus,proto3" json:"consensus,omitempty"`
	// The state_root_hash should match the final state_root after all
	// transactions in the batches have been applied, otherwise the block
	// is not valid
	StateRootHash string `protobuf:"bytes,6,opt,name=state_root_hash,json=stateRootHash" json:"state_root_hash,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockHeader) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockHeader) GetPreviousBlockId() string {
	if m != nil {
		return m.PreviousBlockId
	}
	return ""
}

func (m *BlockHeader) GetSignerPubkey() string {
	if m != nil {
		return m.SignerPubkey
	}
	return ""
}

func (m *BlockHeader) GetBatchIds() []string {
	if m != nil {
		return m.BatchIds
	}
	return nil
}

func (m *BlockHeader) GetConsensus() []byte {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *BlockHeader) GetStateRootHash() string {
	if m != nil {
		return m.StateRootHash
	}
	return ""
}

type Block struct {
	// The serialized version of the BlockHeader
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The signature derived from signing the header
	HeaderSignature string `protobuf:"bytes,2,opt,name=header_signature,json=headerSignature" json:"header_signature,omitempty"`
	// A list of batches. The batches may contain new batches that other
	// validators may not have received yet, or they will be all batches needed
	// for block validation when passed to the journal
	Batches []*batch.Batch `protobuf:"bytes,3,rep,name=batches" json:"batches,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetHeaderSignature() string {
	if m != nil {
		return m.HeaderSignature
	}
	return ""
}

func (m *Block) GetBatches() []*batch.Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "BlockHeader")
	proto.RegisterType((*Block)(nil), "Block")
}

func init() { proto.RegisterFile("sawtooth_sdk/protobuf/block_pb2/block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x33, 0x81, 0xc9, 0x1e, 0x10, 0xb4, 0x89, 0x66, 0x51, 0x0f, 0x04, 0x8d, 0x41, 0x4d,
	0x46, 0x82, 0xdf, 0x80, 0x13, 0x5c, 0x0c, 0x99, 0x37, 0x2f, 0xcd, 0xc6, 0xaa, 0x5b, 0x80, 0x75,
	0xe9, 0x6b, 0x35, 0x7e, 0x59, 0x3f, 0x8b, 0xdd, 0xab, 0xd5, 0x93, 0xb7, 0xd7, 0x5f, 0xff, 0x7d,
	0xef, 0xff, 0x7f, 0x85, 0x07, 0xcc, 0x3e, 0xb4, 0x94, 0xba, 0xe4, 0x58, 0xec, 0xe6, 0x8d, 0x92,
	0x5a, 0xe6, 0xe6, 0x75, 0x9e, 0xef, 0xe5, 0x76, 0xc7, 0x9b, 0x7c, 0xe1, 0xaa, 0x84, 0x2e, 0x2e,
	0xfe, 0x13, 0x67, 0x7a, 0x5b, 0x3a, 0x71, 0x5b, 0x39, 0xf1, 0xf4, 0x2b, 0x80, 0xc1, 0xb2, 0x7d,
	0xbc, 0x12, 0x59, 0x21, 0x14, 0xbb, 0x84, 0xc8, 0x75, 0xad, 0xcd, 0x21, 0x0e, 0x26, 0xc1, 0xac,
	0x9b, 0xf6, 0x09, 0x3c, 0x99, 0x03, 0xbb, 0x87, 0xd3, 0x46, 0x89, 0xf7, 0x4a, 0x1a, 0xe4, 0x4e,
	0x55, 0x15, 0xf1, 0x91, 0x15, 0x45, 0xe9, 0xd8, 0x5f, 0x50, 0xb3, 0x75, 0xc1, 0xae, 0x61, 0x84,
	0xd5, 0x5b, 0x2d, 0x14, 0x6f, 0x4c, 0xbe, 0x13, 0x9f, 0x71, 0x87, 0x74, 0x43, 0x07, 0x37, 0xc4,
	0x68, 0x1a, 0xd9, 0xaa, 0x0a, 0x8c, 0xbb, 0x93, 0x8e, 0x15, 0xf4, 0x09, 0xac, 0x0b, 0x64, 0x57,
	0x10, 0x6d, 0x65, 0x8d, 0xa2, 0x46, 0x83, 0x71, 0xcf, 0xbe, 0x1e, 0xa6, 0x7f, 0x80, 0xdd, 0xc2,
	0x18, 0x75, 0xa6, 0x05, 0x57, 0x36, 0x2a, 0x2f, 0x33, 0x2c, 0xe3, 0x90, 0x26, 0x8c, 0x08, 0xa7,
	0x96, 0xae, 0x2c, 0x9c, 0xee, 0xa1, 0x47, 0x96, 0xd8, 0x39, 0x84, 0x25, 0x65, 0xa4, 0x58, 0xc3,
	0xf4, 0xe7, 0xc4, 0xee, 0xe0, 0xc4, 0x55, 0xbc, 0xb5, 0x96, 0x69, 0xa3, 0x84, 0xcf, 0xe4, 0xf8,
	0xb3, 0xc7, 0x6c, 0x02, 0xc7, 0xe4, 0x4e, 0xa0, 0x4d, 0xd3, 0x99, 0x0d, 0x16, 0x61, 0xb2, 0x6c,
	0xcf, 0xa9, 0xc7, 0xcb, 0x1b, 0x38, 0xf3, 0xdb, 0x4f, 0xec, 0xf6, 0x13, 0xbf, 0xfd, 0x4d, 0xf0,
	0x12, 0xfd, 0xfe, 0x56, 0x1e, 0x12, 0x7e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x25, 0x57, 0x8a,
	0x71, 0xd7, 0x01, 0x00, 0x00,
}
