// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/txn_receipt_pb2/txn_receipt.proto

/*
Package txn_receipt_pb2 is a generated protocol buffer package.

It is generated from these files:
	sawtooth_sdk/protobuf/txn_receipt_pb2/txn_receipt.proto

It has these top-level messages:
	TransactionReceipt
	ClientReceiptGetRequest
	ClientReceiptGetResponse
*/
package txn_receipt_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import state_delta "sawtooth_sdk/protobuf/state_delta_pb2"
import events "sawtooth_sdk/protobuf/events_pb2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientReceiptGetResponse_Status int32

const (
	ClientReceiptGetResponse_OK             ClientReceiptGetResponse_Status = 0
	ClientReceiptGetResponse_INTERNAL_ERROR ClientReceiptGetResponse_Status = 1
	ClientReceiptGetResponse_NO_RESOURCE    ClientReceiptGetResponse_Status = 4
)

var ClientReceiptGetResponse_Status_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
	4: "NO_RESOURCE",
}
var ClientReceiptGetResponse_Status_value = map[string]int32{
	"OK":             0,
	"INTERNAL_ERROR": 1,
	"NO_RESOURCE":    4,
}

func (x ClientReceiptGetResponse_Status) String() string {
	return proto.EnumName(ClientReceiptGetResponse_Status_name, int32(x))
}
func (ClientReceiptGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type TransactionReceipt struct {
	// State changes made by this transaction
	// StateChange is already defined in protos/state_delta.proto
	StateChanges []*state_delta.StateChange `protobuf:"bytes,1,rep,name=state_changes,json=stateChanges" json:"state_changes,omitempty"`
	// Events fired by this transaction
	Events []*events.Event `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	// Transaction family defined data
	Data          []*TransactionReceipt_Data `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	TransactionId string                     `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *TransactionReceipt) Reset()                    { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string            { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()               {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TransactionReceipt) GetStateChanges() []*state_delta.StateChange {
	if m != nil {
		return m.StateChanges
	}
	return nil
}

func (m *TransactionReceipt) GetEvents() []*events.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *TransactionReceipt) GetData() []*TransactionReceipt_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionReceipt) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type TransactionReceipt_Data struct {
	// Interpretation left to transaction family
	DataType string `protobuf:"bytes,1,opt,name=data_type,json=dataType" json:"data_type,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TransactionReceipt_Data) Reset()                    { *m = TransactionReceipt_Data{} }
func (m *TransactionReceipt_Data) String() string            { return proto.CompactTextString(m) }
func (*TransactionReceipt_Data) ProtoMessage()               {}
func (*TransactionReceipt_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TransactionReceipt_Data) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *TransactionReceipt_Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Fetches a specific txn by its id (header_signature) from the blockchain.
type ClientReceiptGetRequest struct {
	TransactionIds []string `protobuf:"bytes,1,rep,name=transaction_ids,json=transactionIds" json:"transaction_ids,omitempty"`
}

func (m *ClientReceiptGetRequest) Reset()                    { *m = ClientReceiptGetRequest{} }
func (m *ClientReceiptGetRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientReceiptGetRequest) ProtoMessage()               {}
func (*ClientReceiptGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientReceiptGetRequest) GetTransactionIds() []string {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

// A response that returns the txn receipt specified by a
// ClientTransactionReceiptGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, txn receipt has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no receipt exists for the transaction id specified
type ClientReceiptGetResponse struct {
	Status   ClientReceiptGetResponse_Status `protobuf:"varint,1,opt,name=status,enum=ClientReceiptGetResponse_Status" json:"status,omitempty"`
	Receipts []*TransactionReceipt           `protobuf:"bytes,2,rep,name=receipts" json:"receipts,omitempty"`
}

func (m *ClientReceiptGetResponse) Reset()                    { *m = ClientReceiptGetResponse{} }
func (m *ClientReceiptGetResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientReceiptGetResponse) ProtoMessage()               {}
func (*ClientReceiptGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientReceiptGetResponse) GetStatus() ClientReceiptGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientReceiptGetResponse_OK
}

func (m *ClientReceiptGetResponse) GetReceipts() []*TransactionReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionReceipt)(nil), "TransactionReceipt")
	proto.RegisterType((*TransactionReceipt_Data)(nil), "TransactionReceipt.Data")
	proto.RegisterType((*ClientReceiptGetRequest)(nil), "ClientReceiptGetRequest")
	proto.RegisterType((*ClientReceiptGetResponse)(nil), "ClientReceiptGetResponse")
	proto.RegisterEnum("ClientReceiptGetResponse_Status", ClientReceiptGetResponse_Status_name, ClientReceiptGetResponse_Status_value)
}

func init() {
	proto.RegisterFile("sawtooth_sdk/protobuf/txn_receipt_pb2/txn_receipt.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0xb5, 0xd0, 0x34, 0x70, 0x81, 0x42, 0xc6, 0x18, 0x1b, 0x4c, 0x0c, 0x69, 0x62, 0x24, 0x46,
	0x87, 0x88, 0x31, 0xf8, 0x2a, 0xd8, 0x18, 0xa2, 0xa1, 0x66, 0xc0, 0x17, 0x5f, 0x26, 0x03, 0x1d,
	0xa5, 0x91, 0xb4, 0x95, 0x99, 0xba, 0xbb, 0xff, 0xb6, 0xbf, 0xb5, 0xef, 0xdb, 0x99, 0x29, 0x0b,
	0x2c, 0xf0, 0x36, 0xf7, 0xdc, 0x73, 0xee, 0xb9, 0x73, 0x73, 0x60, 0x24, 0xd8, 0x95, 0x4c, 0x53,
	0xb9, 0xa6, 0x22, 0xfa, 0x3b, 0xc8, 0xb6, 0xa9, 0x4c, 0x97, 0xf9, 0xef, 0x81, 0xbc, 0x4e, 0xe8,
	0x96, 0xaf, 0x78, 0x9c, 0x49, 0x9a, 0x2d, 0x87, 0x87, 0x35, 0xd6, 0xa4, 0xee, 0x05, 0xa1, 0x90,
	0x4c, 0x72, 0x1a, 0xf1, 0x8d, 0x64, 0x5a, 0x78, 0x50, 0x97, 0xc2, 0x77, 0xe7, 0x85, 0xfc, 0x3f,
	0x4f, 0xa4, 0xd0, 0x1a, 0xf3, 0x34, 0x74, 0xff, 0xce, 0x02, 0xb4, 0xd8, 0xb2, 0x44, 0xb0, 0x95,
	0x8c, 0xd3, 0x84, 0x98, 0x25, 0xd0, 0x7b, 0x68, 0x99, 0xd1, 0xab, 0x35, 0x4b, 0xfe, 0x70, 0xe1,
	0x59, 0xbd, 0x6a, 0xbf, 0x31, 0x6c, 0xe2, 0xb9, 0x42, 0x27, 0x1a, 0x24, 0x4d, 0xb1, 0x2f, 0x04,
	0x7a, 0x09, 0x8e, 0x99, 0xec, 0x55, 0x34, 0xd7, 0xc1, 0x81, 0x2a, 0x49, 0x89, 0xa2, 0xb7, 0x60,
	0x47, 0x4c, 0x32, 0xaf, 0xaa, 0xbb, 0x1e, 0x3e, 0x75, 0xc5, 0x5f, 0x8a, 0x3e, 0xd1, 0x2c, 0xf4,
	0x0a, 0x5c, 0xb9, 0x27, 0xd0, 0x38, 0xf2, 0xec, 0x9e, 0xd5, 0xaf, 0x93, 0xd6, 0x01, 0x3a, 0x8d,
	0xba, 0x23, 0xb0, 0x95, 0x08, 0xbd, 0x80, 0xba, 0x92, 0x51, 0x79, 0x93, 0xf1, 0x62, 0x57, 0xc5,
	0xac, 0x29, 0x60, 0x51, 0xd4, 0x08, 0x95, 0xce, 0x95, 0x02, 0x6f, 0x9a, 0xf9, 0xfe, 0x18, 0x9e,
	0x4f, 0x36, 0xb1, 0xda, 0xcf, 0x78, 0x7f, 0xe5, 0xc5, 0xeb, 0x5f, 0xce, 0x85, 0x44, 0xaf, 0xa1,
	0x7d, 0x6c, 0x6d, 0x7e, 0x5f, 0x27, 0xee, 0x91, 0xb7, 0xf0, 0x6f, 0x2d, 0xf0, 0x4e, 0x87, 0x88,
	0x2c, 0x4d, 0x04, 0x47, 0x9f, 0xc0, 0x51, 0xe7, 0xc9, 0x85, 0x5e, 0xc7, 0x1d, 0xf6, 0xf0, 0x25,
	0xaa, 0xbe, 0x69, 0x2e, 0x48, 0xc9, 0x47, 0x03, 0xa8, 0x95, 0x59, 0xd8, 0x9d, 0xf2, 0xe9, 0x99,
	0x63, 0x91, 0x07, 0x92, 0xff, 0x11, 0x1c, 0x33, 0x02, 0x39, 0x50, 0x09, 0xbf, 0x75, 0x9e, 0x14,
	0x3f, 0x76, 0xa7, 0xb3, 0x45, 0x40, 0x66, 0x9f, 0xbf, 0xd3, 0x80, 0x90, 0x90, 0x74, 0x2c, 0xd4,
	0x86, 0xc6, 0x2c, 0xa4, 0x24, 0x98, 0x87, 0x3f, 0xc9, 0x24, 0xe8, 0xd8, 0xe3, 0x37, 0xf0, 0x6c,
	0x97, 0x15, 0x5c, 0x64, 0x05, 0xef, 0xb2, 0xf2, 0xc3, 0xfa, 0xd5, 0x7e, 0x14, 0xd0, 0xa5, 0xa3,
	0x9b, 0x1f, 0xee, 0x03, 0x00, 0x00, 0xff, 0xff, 0x62, 0x7e, 0xf1, 0x2e, 0xd0, 0x02, 0x00, 0x00,
}
